source 'https://github.com/CocoaPods/Specs.git'

target 'DarkSkyKitExample' do
  use_frameworks!
  pod 'Alamofire', '3.5.0'

  target 'DarkSkyKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
