platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DarkSkyKitExample' do
  use_frameworks!
  pod 'Alamofire', '4.0.0'

  target 'DarkSkyKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
