platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DarkSkyKitExample' do
  use_frameworks!
  pod 'Alamofire', '4.0.0'

  target 'DarkSkyKitExampleTests' do
    inherit! :search_paths
      pod 'OHHTTPStubs', '~> 5.2.1'
      pod 'OHHTTPStubs/Swift', '~> 5.2.1'
    end
end
